exposed to designer padding setting
h4rdmol/ProgressionSystem pull request #43
Opened 2024-12-30 12:13 UTC by h4rdmol

https://trello.com/c/gafWu8QJ/

* removed padding logic
* removed unused logic to display widget in the menu 
* renamed widget from MenuWidget to EndGameWidget 
* sett padding as it is expected from designer side 

![image](https://github.com/user-attachments/assets/82e01aed-8ba7-454f-87bd-a20a5304bd94)

2024-12-30 13:31 UTC, JanSeliv commented
Why do you need padding in data asset? All UI-related data such as paddings should be tweaked right in the user widget, where you also have padding for each widget component

2025-01-02 03:04 UTC, JanSeliv requested changes
We are not going to support prototype functionality in current functional stage, where stars are approved to be shown as 3D in menu

Therefore,

1. Please remove the use of padding and all other related 2D star-logic from Menu
2. Rename MenuWidget to EndGameWidget (including widget asset in content)

2025-01-03 19:43 UTC, h4rdmol commented
* removed padding logic
* removed unused logic to display widget in the menu 
* renamed widget from MenuWidget to EndGameWidget 
* sett padding as it is expected from designer side 

![image](https://github.com/user-attachments/assets/82e01aed-8ba7-454f-87bd-a20a5304bd94)

2025-01-04 02:48 UTC, JanSeliv commented on Source/ProgressionSystemRuntime/Public/Widgets/PSEndGameWidget.h
>   * Widget to display the progression as stars in the main menu.
`in the main menu` - please update description

2025-01-04 02:48 UTC, JanSeliv commented on Source/ProgressionSystemRuntime/Public/Data/PSDataAsset.h
>  	/** Main menu and end-game progression widget */
`/** Main menu ` - please update description

2025-01-04 02:50 UTC, JanSeliv commented on Source/ProgressionSystemRuntime/Public/Data/PSDataAsset.h
> +	FMargin MenuWidgetPaddingInternal = FMargin(0, 0, 0, 0);
You dont need Padding in data asset anymore, please remove `MenuWidgetPaddingInternal` property and `GetMenuWidgetPadding()` function

2025-01-04 02:52 UTC, JanSeliv commented on Source/ProgressionSystemRuntime/Private/Widgets/PSEndGameWidget.cpp
> +	case ECurrentGameState::Menu:
since both `case` do the same, please do `fallthrough`:
```cpp
        case ECurrentGameState::Menu: // Fallthrough
	case ECurrentGameState::GameStarting:
		SetVisibility(ESlateVisibility::Collapsed);
		break;
        default: break;
```

2025-01-04 02:56 UTC, JanSeliv commented on Source/ProgressionSystemRuntime/Public/Widgets/PSEndGameWidget.h
> +class PROGRESSIONSYSTEMRUNTIME_API UPSEndGameWidget : public UUserWidget
Please fix PS End-Game Widget warnings:
![image](https://github.com/user-attachments/assets/8a86a406-0a94-4625-b8f3-4689222ac741)

2025-01-04 21:37 UTC, h4rdmol commented on Source/ProgressionSystemRuntime/Public/Widgets/PSEndGameWidget.h
>   * Widget to display the progression as stars in the main menu.
done https://github.com/h4rdmol/ProgressionSystem/pull/43/commits/f48a0da673c04aea830128a3ab9d506b1f4858c7

2025-01-04 21:51 UTC, h4rdmol commented on Source/ProgressionSystemRuntime/Public/Data/PSDataAsset.h
>  	/** Main menu and end-game progression widget */
done https://github.com/h4rdmol/ProgressionSystem/pull/43/commits/916f3a869934724326a5d17adff9b09e7f6a3656

2025-01-04 21:51 UTC, h4rdmol commented on Source/ProgressionSystemRuntime/Public/Data/PSDataAsset.h
> +	FMargin MenuWidgetPaddingInternal = FMargin(0, 0, 0, 0);
done https://github.com/h4rdmol/ProgressionSystem/pull/43/commits/916f3a869934724326a5d17adff9b09e7f6a3656

2025-01-04 21:52 UTC, h4rdmol commented on Source/ProgressionSystemRuntime/Private/Widgets/PSEndGameWidget.cpp
> +	case ECurrentGameState::Menu:
done https://github.com/h4rdmol/ProgressionSystem/pull/43/commits/eab433dd1885b9fd32e1d2e33091ae42b6b18ad1

2025-01-04 21:55 UTC, h4rdmol commented on Source/ProgressionSystemRuntime/Public/Widgets/PSEndGameWidget.h
> +class PROGRESSIONSYSTEMRUNTIME_API UPSEndGameWidget : public UUserWidget
done https://github.com/h4rdmol/ProgressionSystem/pull/43/commits/36201bc310628b43fe1a6a557348a3c4b2646006

2025-01-04 22:05 UTC, JanSeliv commented on Source/ProgressionSystemRuntime/Private/Widgets/PSEndGameWidget.cpp
> +	case ECurrentGameState::Menu:
@h4rdmol, is not finished yet, compare my example and you logic. Also it's good practive to write `// Fallthrough` comment showing others you did it intentionally

2025-01-04 22:09 UTC, JanSeliv commented on Source/ProgressionSystemRuntime/Public/Widgets/PSEndGameWidget.h
> +class PROGRESSIONSYSTEMRUNTIME_API UPSEndGameWidget : public UUserWidget
@h4rdmol, is not finished yet, only 2 warnings were fixed and 4 still stay in header:

- line 44 requires `enum class ECurrentGameState : uint8;` on the beginning of the  `PSEndGameWidget.h` (before UCLASS), search in bomber examples
- line 52 requires `enum class EEndGameState : uint8;` on the beginning of the  `PSEndGameWidget.h` (before UCLASS), , search in bomber examples
- line 48 requires `class`-forward right before `AMyPlayerState` usage

![image](https://github.com/user-attachments/assets/2e6c5bae-92e5-4299-ab9b-41cbff997885)

2025-01-04 23:10 UTC, h4rdmol commented on Source/ProgressionSystemRuntime/Private/Widgets/PSEndGameWidget.cpp
> +	case ECurrentGameState::Menu:
added https://github.com/h4rdmol/ProgressionSystem/pull/43/commits/c6fb2fa1c22580ec9029ef3ae3b19fa6e2461476

2025-01-04 23:48 UTC, h4rdmol commented on Source/ProgressionSystemRuntime/Public/Widgets/PSEndGameWidget.h
> +class PROGRESSIONSYSTEMRUNTIME_API UPSEndGameWidget : public UUserWidget
fixed https://github.com/h4rdmol/ProgressionSystem/pull/43/commits/2f721df80cc5d382704d0a3a257c198ba8b71824

2025-01-05 00:04 UTC, merged